server:
  port: 88

spring:
  cloud:
    gateway:
      routes:
        - id: wms_route
          uri: lb://gulimall-wms
          predicates:
            - Path=/wms/**
        - id: gulimall-ums_route
          uri: lb://gulimall-ums
          predicates:
            - Path=/ums/**
        - id: gulimall-sms_route
          uri: lb://gulimall-sms
          predicates:
            - Path=/sms/**
        - id: gulimall-oms_route
          uri: lb://gulimall-oms
          predicates:
            - Path=/oms/**
        - id: pms_route
          uri: lb://gulimall-pms
          predicates:
            - Path=/pms/**
